package com.simplj.flair.cache.serial.codecs;

import com.simplj.flair.cache.serial.Codec;
import com.simplj.flair.cache.serial.CodecRegistry;

import java.lang.reflect.*;
import java.nio.ByteBuffer;
import java.util.*;

/**
 * A {@link Codec} generated by inspecting a class's structure at runtime via reflection.
 *
 * <p>Intended for prototyping only. Production code should use {@link CompositeCodec} explicitly.
 * See {@link com.simplj.flair.cache.serial.Codecs#reflect(Class)} for full documentation of
 * requirements and limitations.
 *
 * <p><strong>Wire ordering contract:</strong>
 * <ul>
 *   <li>For records: components are encoded in declaration order.</li>
 *   <li>For regular classes: fields are encoded alphabetically within each class-hierarchy
 *       level, starting from the topmost ancestor down to the concrete class.</li>
 * </ul>
 *
 * <h3>Deliberately unsupported types</h3>
 *
 * <p><strong>Object arrays ({@code String[]}, {@code Integer[]}, {@code MyPojo[]}, etc.)
 * are not supported. Use {@code List<T>} instead.</strong>
 * Java arrays are unsoundly covariant — {@code String[]} is assignable to {@code Object[]},
 * which allows inserting a non-String element at runtime and causes an
 * {@link ArrayStoreException} that the compiler cannot catch. {@code List<T>} carries
 * exactly the same information without that pitfall, and is fully supported by this module
 * via {@link ListCodec}. For sets, use {@link SetCodec}.
 *
 * <p><strong>Atomic and accumulator types ({@code AtomicInteger}, {@code AtomicLong},
 * {@code AtomicBoolean}, {@code AtomicReference}, {@code LongAdder}, {@code DoubleAdder},
 * etc.) are not supported.</strong>
 * These are concurrency primitives, not data containers. Their only value when serialized
 * is the snapshot of the wrapped primitive — the atomicity guarantee is meaningless once
 * the value crosses a wire or JVM boundary. A serializable class that holds an
 * {@code AtomicInteger} field has a design issue: replace it with a plain {@code int}.
 * The concurrent wrapper belongs in the live, in-memory class; the serializable form
 * should use the plain primitive.
 */
public final class ReflectiveCodec<T> implements Codec<T> {

    private final List<ReflectiveField> fields;
    private final Constructor<T> constructor;
    private final boolean isRecord;

    /**
     * Constructs a codec for {@code type}, registering it in {@code registry} immediately so
     * that circular field references can be resolved without infinite recursion.
     */
    @SuppressWarnings("unchecked")
    public ReflectiveCodec(Class<T> type, CodecRegistry registry) {
        // Self-register before resolving field codecs: if a field references 'type' (directly or
        // transitively), resolveCodec() will find this codec in the registry instead of looping.
        registry.register(type, this);
        try {
            this.isRecord = type.isRecord();
            if (isRecord) {
                this.constructor = findCanonicalConstructor(type);
                this.fields = buildRecordFields(type, registry);
            } else {
                this.constructor = findNoArgConstructor(type);
                this.fields = buildPojoFields(type, registry);
            }
        } catch (RuntimeException e) {
            // Roll back the self-registration so the registry doesn't retain a broken codec.
            // Without this, a second reflect() call would return the broken instance via lookup()
            // and then throw a NullPointerException instead of the original clear error.
            registry.deregister(type);
            throw e;
        }
    }

    // ── Codec ─────────────────────────────────────────────────────────────────

    @Override
    @SuppressWarnings({"unchecked", "rawtypes"})
    public void serialize(T obj, ByteBuffer buf) {
        for (ReflectiveField rf : fields) {
            ((Codec) rf.codec).serialize(rf.getValue(obj), buf);
        }
    }

    @Override
    @SuppressWarnings({"unchecked", "rawtypes"})
    public int sizeOf(T obj) {
        int size = 0;
        for (ReflectiveField rf : fields) {
            size += ((Codec) rf.codec).sizeOf(rf.getValue(obj));
        }
        return size;
    }

    @Override
    public T deserialize(ByteBuffer buf) {
        Object[] values = new Object[fields.size()];
        for (int i = 0; i < fields.size(); i++) {
            values[i] = fields.get(i).codec.deserialize(buf);
        }
        try {
            if (isRecord) {
                return constructor.newInstance(values);
            }
            T obj = constructor.newInstance();
            for (int i = 0; i < fields.size(); i++) {
                fields.get(i).field.set(obj, values[i]);
            }
            return obj;
        } catch (ReflectiveOperationException e) {
            throw new RuntimeException(
                    "Failed to construct " + constructor.getDeclaringClass().getSimpleName(), e);
        }
    }

    // ── Field collection ──────────────────────────────────────────────────────

    private static List<ReflectiveField> buildRecordFields(Class<?> type, CodecRegistry registry) {
        RecordComponent[] components = type.getRecordComponents();
        List<ReflectiveField> result = new ArrayList<>(components.length);
        for (RecordComponent rc : components) {
            Method accessor = rc.getAccessor();
            accessor.setAccessible(true);
            result.add(new ReflectiveField(rc.getName(), resolveCodec(rc.getGenericType(), registry), accessor, null));
        }
        return result;
    }

    private static List<ReflectiveField> buildPojoFields(Class<?> type, CodecRegistry registry) {
        // Walk hierarchy from topmost ancestor down to the concrete class; within each level,
        // sort fields alphabetically for a stable, documented wire order.
        Deque<Class<?>> hierarchy = new ArrayDeque<>();
        for (Class<?> c = type; c != null && c != Object.class; c = c.getSuperclass()) {
            hierarchy.addFirst(c);
        }

        List<ReflectiveField> result = new ArrayList<>();
        for (Class<?> c : hierarchy) {
            List<Field> level = new ArrayList<>();
            for (Field f : c.getDeclaredFields()) {
                int mod = f.getModifiers();
                if (Modifier.isStatic(mod) || Modifier.isTransient(mod)) continue;
                if (Modifier.isFinal(mod)) {
                    throw new IllegalArgumentException(
                            "ReflectiveCodec cannot write to final field '"
                            + f.getName() + "' in " + type.getSimpleName()
                            + ". Declare it as a Java record, or remove 'final'.");
                }
                level.add(f);
            }
            level.sort(Comparator.comparing(Field::getName));
            for (Field f : level) {
                f.setAccessible(true);
                result.add(new ReflectiveField(f.getName(), resolveCodec(f.getGenericType(), registry), null, f));
            }
        }
        return result;
    }

    // ── Codec resolution ──────────────────────────────────────────────────────

    @SuppressWarnings({"unchecked", "rawtypes"})
    static Codec<?> resolveCodec(Type type, CodecRegistry registry) {
        if (type instanceof ParameterizedType) {
            ParameterizedType pt = (ParameterizedType) type;
            Class<?> raw = (Class<?>) pt.getRawType();
            Type[] args = pt.getActualTypeArguments();
            if (raw == List.class) {
                return new ListCodec<>(resolveCodec(args[0], registry));
            }
            if (raw == Set.class) {
                return new SetCodec<>(resolveCodec(args[0], registry));
            }
            if (raw == Map.class) {
                return new MapCodec<>(resolveCodec(args[0], registry), resolveCodec(args[1], registry));
            }
            if (raw == Optional.class) {
                return new OptionalCodec<>(resolveCodec(args[0], registry));
            }
            if (raw == Collection.class || raw == Iterable.class) {
                throw new IllegalArgumentException(
                        "ReflectiveCodec does not support '" + raw.getSimpleName() + "<T>' fields. "
                        + "Declare the field as List<T> or Set<T> to make the collection type explicit "
                        + "and avoid a runtime ClassCastException.");
            }
            throw new IllegalArgumentException(
                    "ReflectiveCodec does not support parameterized type '" + type
                    + "'. Supported generic containers: List<T>, Set<T>, Map<K,V>, Optional<T>.");
        }

        if (type instanceof WildcardType) {
            throw new IllegalArgumentException(
                    "ReflectiveCodec cannot resolve wildcard type '" + type
                    + "'. Use a concrete type bound "
                    + "(e.g. List<String> instead of List<? extends String>).");
        }

        if (type instanceof TypeVariable) {
            throw new IllegalArgumentException(
                    "ReflectiveCodec cannot resolve unbound type variable '" + type
                    + "'. Use a concrete type.");
        }

        if (!(type instanceof Class)) {
            throw new IllegalArgumentException("Unsupported reflective type: " + type);
        }

        Class<?> cls = (Class<?>) type;

        // Primitive scalars — direct mapping, no registry lookup, no boxing.
        if (cls == byte.class)    return PrimitiveCodecs.BYTE;
        if (cls == short.class)   return PrimitiveCodecs.SHORT;
        if (cls == int.class)     return PrimitiveCodecs.INT;
        if (cls == long.class)    return PrimitiveCodecs.LONG;
        if (cls == float.class)   return PrimitiveCodecs.FLOAT;
        if (cls == double.class)  return PrimitiveCodecs.DOUBLE;
        if (cls == boolean.class) return PrimitiveCodecs.BOOLEAN;
        if (cls == char.class)    return PrimitiveCodecs.CHAR;

        // Primitive arrays — handled before the generic array check below.
        if (cls == byte[].class)    return ByteArrayCodec.INSTANCE;
        if (cls == int[].class)     return PrimitiveArrayCodecs.INT;
        if (cls == long[].class)    return PrimitiveArrayCodecs.LONG;
        if (cls == double[].class)  return PrimitiveArrayCodecs.DOUBLE;
        if (cls == float[].class)   return PrimitiveArrayCodecs.FLOAT;
        if (cls == short[].class)   return PrimitiveArrayCodecs.SHORT;
        if (cls == char[].class)    return PrimitiveArrayCodecs.CHAR;
        if (cls == boolean[].class) return PrimitiveArrayCodecs.BOOLEAN;

        // Object arrays are not supported — see class Javadoc for the reason.
        if (cls.isArray()) {
            throw new IllegalArgumentException(
                    "Object array type '" + cls.getComponentType().getSimpleName()
                    + "[]' is not supported by ReflectiveCodec. "
                    + "Use List<" + cls.getComponentType().getSimpleName() + "> instead "
                    + "(same information, no array covariance pitfalls). See ReflectiveCodec Javadoc.");
        }

        // Atomic and accumulator types are not supported — see class Javadoc for the reason.
        if (isConcurrencyPrimitive(cls)) {
            throw new IllegalArgumentException(
                    "Atomic/accumulator type '" + cls.getSimpleName()
                    + "' cannot be reflectively serialized. "
                    + "Replace with its plain primitive equivalent (e.g. int instead of AtomicInteger). "
                    + "See ReflectiveCodec Javadoc.");
        }

        if (cls.isEnum()) {
            // Safe: EnumCodec checks ordinal bounds at construction time.
            return new EnumCodec(cls);
        }

        // Boxed primitives, String, UUID, Instant, date/time types, BigDecimal, BigInteger,
        // and any hand-registered codec — all resolved via registry.
        Codec<?> registered = registry.lookup(cls);
        if (registered != null) return registered;

        // Unknown custom type: generate a new ReflectiveCodec and register it.
        // Self-registration inside the ReflectiveCodec constructor prevents re-entry
        // if this type is encountered again while resolving its own fields.
        return new ReflectiveCodec<>(cls, registry);
    }

    // ── Concurrency-primitive detection ──────────────────────────────────────

    private static final Set<String> ACCUMULATOR_NAMES = new HashSet<>(Arrays.asList(
            "LongAdder", "DoubleAdder", "LongAccumulator", "DoubleAccumulator"));

    private static boolean isConcurrencyPrimitive(Class<?> cls) {
        String pkg = cls.getPackageName();
        if ("java.util.concurrent.atomic".equals(pkg)) return true;
        if ("java.util.concurrent".equals(pkg) && ACCUMULATOR_NAMES.contains(cls.getSimpleName())) return true;
        return false;
    }

    // ── Constructor discovery ─────────────────────────────────────────────────

    @SuppressWarnings("unchecked")
    private static <T> Constructor<T> findCanonicalConstructor(Class<T> type) {
        RecordComponent[] components = type.getRecordComponents();
        Class<?>[] paramTypes = Arrays.stream(components)
                .map(RecordComponent::getType)
                .toArray(Class[]::new);
        try {
            Constructor<T> c = type.getDeclaredConstructor(paramTypes);
            c.setAccessible(true);
            return c;
        } catch (NoSuchMethodException e) {
            throw new IllegalArgumentException(
                    "Cannot find canonical constructor for record " + type.getSimpleName(), e);
        }
    }

    @SuppressWarnings("unchecked")
    private static <T> Constructor<T> findNoArgConstructor(Class<T> type) {
        try {
            Constructor<T> c = type.getDeclaredConstructor();
            c.setAccessible(true);
            return c;
        } catch (NoSuchMethodException e) {
            throw new IllegalArgumentException(
                    "ReflectiveCodec requires a no-arg constructor; "
                    + type.getSimpleName() + " has none. Declare one or convert to a Java record.", e);
        }
    }

    // ── Field descriptor ──────────────────────────────────────────────────────

    private static final class ReflectiveField {
        final String name;
        final Codec<?> codec;
        final Method accessor; // non-null for record components
        final Field field;     // non-null for POJO fields

        ReflectiveField(String name, Codec<?> codec, Method accessor, Field field) {
            this.name = name;
            this.codec = codec;
            this.accessor = accessor;
            this.field = field;
        }

        Object getValue(Object obj) {
            try {
                return accessor != null ? accessor.invoke(obj) : field.get(obj);
            } catch (ReflectiveOperationException e) {
                throw new RuntimeException("Failed to read field '" + name + "'", e);
            }
        }
    }
}
